'use strict';
const APP_VERSION='3.20.0-nav-premium',DB_NAME='santa-teresa-secure-vault',STORE='kv',KDF_ITERATIONS=250000,AUTO_LOCK_MS=600000,MAX_PHOTO_BYTES=900*1024,PHOTO_MAX_SIDE=1400;window.SANTA_TERESA_APP_VERSION=APP_VERSION;
const $=id=>document.getElementById(id);
const state={db:null,meta:null,key:null,residents:[],selectedId:null,photoDataUrl:'',photoRemoved:false,timer:null,dirty:false,step:0,deferredInstall:null};
const fields=['nombre','habitacion','fechaNacimiento','referente','contacto','estado','resumen','bien','incomoda','claves','comunicacion','movilidad','alimentacion','sueno','alergias','alertas','observaciones'];
const defaults={nombre:'',habitacion:'',fechaNacimiento:'',referente:'',contacto:'',estado:'Activa',resumen:'',bien:'',incomoda:'',claves:'',comunicacion:'',movilidad:'',alimentacion:'',sueno:'',alergias:'',alertas:'',observaciones:''};
const steps=[
  {title:'Paso 1 · Datos básicos',help:'Empieza por los datos mínimos. La ficha se puede completar poco a poco y guardar cuando quieras.'},
  {title:'Paso 2 · Bienestar y trato',help:'Añade lo que le tranquiliza, lo que le incomoda y las claves principales para cuidarle mejor.'},
  {title:'Paso 3 · Cuidados importantes',help:'Completa comunicación, movilidad, alimentación, sueño, alergias, alertas y observaciones.'},
  {title:'Paso 4 · Resultado final',help:'Revisa la ficha con su formato final de colores antes de guardar o imprimir.'}
];
function iso(){return new Date().toISOString()}function fmt(v){try{return v?new Intl.DateTimeFormat('es-ES',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)):'—'}catch{return v||'—'}}function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(16).slice(2)}
function b64(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s)}function unb64(s){const bin=atob(s);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return bytes}const enc=s=>new TextEncoder().encode(s),dec=b=>new TextDecoder().decode(b);
function view(id){['setupView','unlockView','appView'].forEach(v=>$(v).classList.add('hidden'));$(id).classList.remove('hidden');const nav=$('bottomNav');if(nav)nav.classList.toggle('hidden',id!=='appView')}function status(id,msg,type='ok'){const el=$(id);if(!el)return;el.textContent=msg;el.className='status '+type;el.hidden=false}function hide(id){const el=$(id);if(el)el.hidden=true}
function resetLock(){if(!state.key)return;clearTimeout(state.timer);state.timer=setTimeout(()=>lock('Bloqueo automático por inactividad.'),AUTO_LOCK_MS)}['click','keydown','input','pointerdown'].forEach(e=>addEventListener(e,resetLock,{passive:true}));
function openDb(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'key'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function store(m='readonly'){return state.db.transaction(STORE,m).objectStore(STORE)}function get(k){return new Promise((res,rej)=>{const r=store().get(k);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}function put(v){return new Promise((res,rej)=>{const r=store('readwrite').put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}function del(k){return new Promise((res,rej)=>{const r=store('readwrite').delete(k);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}function all(){return new Promise((res,rej)=>{const r=store().getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function keyFromPass(pass,salt){const material=await crypto.subtle.importKey('raw',enc(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:unb64(salt),iterations:KDF_ITERATIONS,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}async function seal(key,obj){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc(JSON.stringify(obj)));return{iv:b64(iv),data:b64(new Uint8Array(data))}}async function openBox(key,box){const clear=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},key,unb64(box.data));return JSON.parse(dec(new Uint8Array(clear)))}
async function createVault(){hide('setupStatus');const p1=$('setupPassword').value,p2=$('setupPassword2').value,name=$('setupVaultName').value.trim()||'Residencia Santa Teresa';if(!$('setupAccept').checked)return status('setupStatus','Marca la casilla de responsabilidad.','err');if(p1.length<10)return status('setupStatus','La contraseña maestra debe tener al menos 10 caracteres.','err');if(p1!==p2)return status('setupStatus','Las contraseñas no coinciden.','err');const salt=b64(crypto.getRandomValues(new Uint8Array(16))),key=await keyFromPass(p1,salt),verifier=await seal(key,{ok:true,createdAt:iso()});const meta={key:'meta',type:'meta',app:'santa-teresa-local-secure',version:APP_VERSION,vaultName:name,createdAt:iso(),updatedAt:iso(),kdf:{name:'PBKDF2',hash:'SHA-256',iterations:KDF_ITERATIONS,salt},verifier};await put(meta);$('setupPassword').value='';$('setupPassword2').value='';await enter(meta,key)}
async function unlock(){hide('unlockStatus');const meta=await get('meta');if(!meta)return init();try{const key=await keyFromPass($('unlockPassword').value,meta.kdf.salt);const check=await openBox(key,meta.verifier);if(!check.ok)throw Error('bad');$('unlockPassword').value='';await enter(meta,key)}catch{status('unlockStatus','Contraseña incorrecta o base dañada.','err')}}async function enter(meta,key){state.meta=meta;state.key=key;$('vaultTitle').textContent=meta.vaultName||'Base local cifrada';$('vaultMeta').textContent=`Creada ${fmt(meta.createdAt)} · bloqueo automático 10 min`;$('unlockVaultName').textContent=meta.vaultName||'Base local cifrada';await loadResidents();clearForm();view('appView');setScreenSafe('home');resetLock()}function lock(msg='Base bloqueada.'){state.key=null;state.residents=[];state.selectedId=null;state.photoDataUrl='';clearTimeout(state.timer);clearForm();view('unlockView');if(msg)status('unlockStatus',msg,'ok')}
async function loadResidents(){const rows=await all();const list=[];for(const row of rows){if(row.type!=='resident')continue;try{list.push(await openBox(state.key,row.box))}catch(e){console.warn('Ficha no descifrable',row.key)}}list.sort((a,b)=>(a.nombre||'').localeCompare(b.nombre||'','es'));state.residents=list;renderList();renderStats()}
function lines(t){return String(t||'').split(/\n+/).map(x=>x.trim()).filter(Boolean)}function joined(v){return Array.isArray(v)?v.join('\n'):(v||'')}function existing(){return state.residents.find(r=>r.id===state.selectedId)||null}
function formToObj(old=null){const o={id:old?.id||uid(),createdAt:old?.createdAt||iso(),updatedAt:iso(),history:Array.isArray(old?.history)?old.history:[],photoDataUrl:state.photoRemoved?'':(state.photoDataUrl||old?.photoDataUrl||'')};for(const f of fields)o[f]=$(f).value.trim();o.bien=lines($('bien').value);o.incomoda=lines($('incomoda').value);o.claves=lines($('claves').value);return o}
function fill(o){for(const f of fields){if(['bien','incomoda','claves'].includes(f))$(f).value=joined(o[f]);else $(f).value=o[f]||defaults[f]||''}state.photoDataUrl=o.photoDataUrl||'';state.photoRemoved=false;renderPhoto();preview();state.dirty=false;setStep(0)}function clearForm(){for(const f of fields)if($(f))$(f).value=defaults[f]||'';state.selectedId=null;state.photoDataUrl='';state.photoRemoved=false;$('photoInput').value='';$('currentFichaLabel').textContent='Nueva ficha';$('deleteFichaBtn').disabled=true;renderPhoto();preview();state.dirty=false;setStep(0);document.querySelectorAll('.resident-item').forEach(el=>el.classList.remove('active'))}
async function saveFicha(){hide('appStatus');if(!state.key)return lock('Sesión caducada.');const old=existing(),o=formToObj(old);if(!o.nombre){setStep(0);setScreenSafe('form');return status('appStatus','El nombre es obligatorio para guardar la ficha.','err')}o.history.push({ts:iso(),action:old?'Ficha actualizada':'Ficha creada'});const box=await seal(state.key,o);await put({key:'resident:'+o.id,type:'resident',id:o.id,updatedAt:o.updatedAt,box});state.selectedId=o.id;await loadResidents();selectFicha(o.id,false);status('appStatus','Ficha guardada en la base local cifrada.','ok')}
function selectFicha(id,goFirst=true){const o=state.residents.find(r=>r.id===id);if(!o)return;state.selectedId=id;fill(o);$('currentFichaLabel').textContent=(o.nombre||'Sin nombre')+(o.habitacion?' · Hab. '+o.habitacion:'');$('deleteFichaBtn').disabled=false;document.querySelectorAll('.resident-item').forEach(el=>el.classList.toggle('active',el.dataset.id===id));if(goFirst)showForm()}
async function deleteFicha(){if(!state.selectedId)return;const o=existing();if(!confirm(`¿Borrar la ficha de "${o?.nombre||'residente'}"?`))return;await del('resident:'+state.selectedId);await loadResidents();clearForm();setScreenSafe('db');status('appStatus','Ficha eliminada.','ok')}function renderStats(){const total=state.residents.length,active=state.residents.filter(r=>(r.estado||'Activa')==='Activa').length,review=state.residents.filter(r=>(r.estado||'')==='Revisión').length,archived=state.residents.filter(r=>(r.estado||'')==='Archivada').length;[['totalStat',total],['activeStat',active],['reviewStat',review],['archivedStat',archived]].forEach(([id,val])=>{const el=$(id);if(el)el.textContent=val})}
function renderList(){const ul=$('residentList'),q=$('searchBox').value.trim().toLowerCase();$('residentCount').textContent=`${state.residents.length} ficha${state.residents.length===1?'':'s'}`;ul.innerHTML='';const f=state.residents.filter(r=>`${r.nombre||''} ${r.habitacion||''} ${r.estado||''}`.toLowerCase().includes(q));if(!f.length){ul.innerHTML='<li class="empty">No hay fichas que mostrar.</li>';return}for(const r of f){const li=document.createElement('li');li.className='resident-item';li.dataset.id=r.id;li.innerHTML='<button type="button"><strong></strong><span></span><small></small></button>';li.querySelector('strong').textContent=r.nombre||'Sin nombre';li.querySelector('span').textContent=`${r.habitacion?'Hab. '+r.habitacion+' · ':''}${r.estado||'Activa'}`;li.querySelector('small').textContent='Actualizada '+fmt(r.updatedAt);li.querySelector('button').onclick=()=>{selectFicha(r.id);setScreenSafe('form')};ul.appendChild(li)}}
function renderPhoto(){const img=$('photoPreview'),empty=$('photoEmpty'),choose=$('choosePhotoBtn');if(state.photoDataUrl){img.src=state.photoDataUrl;img.hidden=false;empty.hidden=true;if(choose)choose.textContent='Cambiar foto'}else{img.removeAttribute('src');img.hidden=true;empty.hidden=false;if(choose)choose.textContent='Añadir foto'}}function esc(t){const d=document.createElement('div');d.textContent=t||'';return d.innerHTML}function listHtml(v){const a=Array.isArray(v)?v:lines(v);return a.length?'<ul>'+a.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p class="muted">Sin datos.</p>'}
function preview(){const o=formToObj(existing());$('printTitle').textContent=o.nombre||'Nueva ficha';$('printSubtitle').textContent=o.habitacion?'Habitación '+o.habitacion:'Ficha de cuidados personalizada';['Nombre','Habitacion','Estado','Referente','Contacto'].forEach(k=>{$('p'+k).textContent=o[k.charAt(0).toLowerCase()+k.slice(1)]||'—'});$('pResumen').textContent=o.resumen||'Sin resumen.';$('pBien').innerHTML=listHtml(o.bien);$('pIncomoda').innerHTML=listHtml(o.incomoda);$('pClaves').innerHTML=listHtml(o.claves);['Comunicacion','Movilidad','Alimentacion','Sueno','Alergias','Alertas','Observaciones'].forEach(k=>{$('p'+k).textContent=o[k.charAt(0).toLowerCase()+k.slice(1)]||'Sin datos.'});$('pUpdated').textContent='Última actualización: '+fmt(o.updatedAt);const img=$('printPhoto'),emp=$('printPhotoEmpty');if(o.photoDataUrl){img.src=o.photoDataUrl;img.hidden=false;emp.hidden=true}else{img.hidden=true;emp.hidden=false}}
async function photo(file){if(!file)return;hide('appStatus');if(!file.type.startsWith('image/')){ $('photoInput').value=''; return status('appStatus','El archivo seleccionado no es una imagen.','err')}try{state.photoDataUrl=await preparePhoto(file);state.photoRemoved=false;renderPhoto();dirty();if(file.size>MAX_PHOTO_BYTES)status('appStatus','Foto reducida automaticamente para guardarla cifrada.','ok')}catch(err){console.error(err);state.photoDataUrl='';$('photoInput').value='';renderPhoto();status('appStatus','No se ha podido preparar la foto. Prueba con JPG o PNG.','err')}}
async function preparePhoto(file){const dataUrl=await readFileDataUrl(file);if(file.size<=MAX_PHOTO_BYTES)return dataUrl;const img=await loadImage(dataUrl),scale=Math.min(1,PHOTO_MAX_SIDE/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);for(const q of [.82,.72,.62,.52,.42]){const out=canvas.toDataURL('image/jpeg',q);if(dataUrlBytes(out)<=MAX_PHOTO_BYTES)return out}return canvas.toDataURL('image/jpeg',.36)}
function readFileDataUrl(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file)})}
function loadImage(src){return new Promise((res,rej)=>{const img=new Image();img.onload=()=>res(img);img.onerror=rej;img.src=src})}
function dataUrlBytes(value){const i=String(value).indexOf(',');return Math.ceil(((i>=0?value.length-i-1:value.length)*3)/4)}
function dirty(){state.dirty=true;preview()}function printFicha(){preview();setStep(3);setScreenSafe('preview');setTimeout(()=>window.print(),120)}
function setStep(n){state.step=Math.max(0,Math.min(steps.length-1,n));const last=state.step===steps.length-1;document.querySelectorAll('[data-step]').forEach(el=>el.classList.toggle('hidden',Number(el.dataset.step)!==state.step));document.querySelectorAll('[data-go-step]').forEach(btn=>btn.classList.toggle('active',Number(btn.dataset.goStep)===state.step));$('stepTitle').textContent=steps[state.step].title;$('stepHelp').textContent=steps[state.step].help;$('stepCounter').textContent=`${state.step+1} de ${steps.length}`;$('progressFill').style.width=((state.step+1)/steps.length*100)+'%';$('prevStepBtn').disabled=state.step===0;$('nextStepBtn').textContent=last?'Ver resultado':'Siguiente';preview()}
function showPreview(){preview();setStep(3);setScreenSafe('preview')}function showForm(){setScreenSafe('form');if(state.step===3)setStep(0);else setStep(state.step)}function nextStep(){if(state.step>=steps.length-1){showPreview();return}setStep(state.step+1);setScreenSafe('form')}function prevStep(){setStep(state.step-1);setScreenSafe('form')}
async function exportBackup(){const rows=await all();const data={kind:'santa-teresa-encrypted-backup',version:APP_VERSION,exportedAt:iso(),warning:'Copia cifrada. Guarda la contraseña maestra por separado.',rows};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='copia-cifrada-santa-teresa-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}async function importBackup(file){if(!file)return;let data;try{data=JSON.parse(await file.text())}catch{return status('unlockStatus','El archivo no es JSON válido.','err')}if(data.kind!=='santa-teresa-encrypted-backup'||!Array.isArray(data.rows))return status('unlockStatus','No parece una copia cifrada válida.','err');if(!confirm('Esto sustituirá la base local de este navegador. ¿Continuar?'))return;state.db.close();await new Promise((res,rej)=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=res;r.onerror=()=>rej(r.error);r.onblocked=()=>rej(Error('Cierra otras pestañas de la app.'))});state.db=await openDb();for(const row of data.rows)await put(row);state.key=null;state.meta=null;await init();status('unlockStatus','Copia importada. Introduce su contraseña maestra.','ok')}
async function changePassword(){hide('passwordStatus');if(!state.key||!state.meta)return lock('Sesión caducada.');const cur=$('currentPassword').value,n1=$('newPassword').value,n2=$('newPassword2').value;if(n1.length<10)return status('passwordStatus','La nueva contraseña debe tener al menos 10 caracteres.','err');if(n1!==n2)return status('passwordStatus','Las nuevas contraseñas no coinciden.','err');try{const test=await keyFromPass(cur,state.meta.kdf.salt);await openBox(test,state.meta.verifier)}catch{return status('passwordStatus','La contraseña actual no es correcta.','err')}const salt=b64(crypto.getRandomValues(new Uint8Array(16))),newKey=await keyFromPass(n1,salt),meta={...state.meta,updatedAt:iso(),version:APP_VERSION,kdf:{...state.meta.kdf,salt,iterations:KDF_ITERATIONS},verifier:await seal(newKey,{ok:true,changedAt:iso()})};await put(meta);for(const o of state.residents){o.history=o.history||[];o.history.push({ts:iso(),action:'Contraseña maestra cambiada; ficha recifrada'});await put({key:'resident:'+o.id,type:'resident',id:o.id,updatedAt:o.updatedAt,box:await seal(newKey,o)})}state.meta=meta;state.key=newKey;$('currentPassword').value=$('newPassword').value=$('newPassword2').value='';status('passwordStatus','Contraseña cambiada y fichas recifradas.','ok')}
async function wipe(){if(prompt('Para borrar toda la base local escribe BORRAR')!=='BORRAR')return;state.key=null;if(state.db)state.db.close();await new Promise((res,rej)=>{const r=indexedDB.deleteDatabase(DB_NAME);r.onsuccess=res;r.onerror=()=>rej(r.error);r.onblocked=()=>rej(Error('Cierra otras pestañas.'))});state.db=await openDb();await init()}
function showInstallButtons(){document.querySelectorAll('.installAppBtn').forEach(btn=>btn.classList.remove('hidden'))}async function installApp(){if(!state.deferredInstall){alert('En este dispositivo usa el menú del navegador y pulsa “Añadir a pantalla de inicio” o “Instalar app”.');return}state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;document.querySelectorAll('.installAppBtn').forEach(btn=>btn.classList.add('hidden'))}
function setScreenSafe(screen){if(typeof window.setSantaScreen==='function')window.setSantaScreen(screen);else{const app=$('appView');if(app){app.classList.remove('screen-home','screen-user','screen-form','screen-db','screen-settings','screen-preview','preview-mode');app.classList.add('screen-'+screen);if(screen==='preview')app.classList.add('preview-mode')}}}
function bind(){addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;showInstallButtons()});$('createVaultBtn').onclick=createVault;$('unlockBtn').onclick=unlock;$('unlockPassword').onkeydown=e=>{if(e.key==='Enter')unlock()};$('lockBtn').onclick=()=>lock();$('newFichaBtn').onclick=()=>{clearForm();setScreenSafe('form')};$('heroNewFichaBtn').onclick=()=>{clearForm();setScreenSafe('form')};$('saveFichaBtn').onclick=saveFicha;$('deleteFichaBtn').onclick=deleteFicha;$('printFichaBtn').onclick=printFicha;$('previewFichaBtn').onclick=showPreview;$('previewPrintBtn').onclick=printFicha;$('previewSaveBtn').onclick=saveFicha;$('backToFormBtn').onclick=()=>{setStep(Math.min(state.step,2));setScreenSafe('form')};$('prevStepBtn').onclick=prevStep;$('nextStepBtn').onclick=nextStep;document.querySelectorAll('[data-go-step]').forEach(btn=>btn.onclick=()=>{const n=Number(btn.dataset.goStep);setStep(n);if(n===3)setScreenSafe('preview');else setScreenSafe('form')});document.querySelectorAll('.installAppBtn').forEach(btn=>btn.onclick=installApp);$('exportBackupBtn').onclick=exportBackup;$('importBackupBtn').onclick=()=>$('backupInput').click();$('backupInput').onchange=e=>importBackup(e.target.files[0]);$('changePasswordBtn').onclick=changePassword;$('wipeBtn').onclick=wipe;$('searchBox').oninput=renderList;$('choosePhotoBtn').onclick=()=>$('photoInput').click();$('photoInput').onchange=e=>photo(e.target.files[0]);$('removePhotoBtn').onclick=()=>{state.photoDataUrl='';state.photoRemoved=true;$('photoInput').value='';renderPhoto();dirty()};fields.forEach(f=>$(f).addEventListener('input',dirty));addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}})}async function init(){state.db=state.db||await openDb();const meta=await get('meta');$('appVersion').textContent=APP_VERSION;const nav=$('bottomNav');if(nav)nav.classList.add('hidden');if(matchMedia('(display-mode: standalone)').matches)document.querySelectorAll('.installAppBtn').forEach(btn=>btn.classList.add('hidden'));if(meta){$('unlockVaultName').textContent=meta.vaultName||'Base local cifrada';view('unlockView')}else view('setupView')}
document.addEventListener('DOMContentLoaded',async()=>{bind();try{if('serviceWorker'in navigator)await navigator.serviceWorker.register('./sw.js')}catch(e){console.warn(e)}try{await init()}catch(e){console.error(e);document.body.innerHTML='<main class="fatal"><h1>Error al iniciar</h1><p>No se ha podido abrir la base local del navegador.</p></main>'}});
